<!-- Barra de Navegação -->
		<nav class="nav1" style="background-color: 	#8A2BE2;">
			<img src="img/logo.png" height="130em" width="300em" style="margin: 0.5em;">
			<b><a href="sobreNos.php" style="color: gold;">Sobre Nós</a>
			<a href="sobreOsite.php" style="color: gold;">| Sobre o Site</a>
			<a href="instrucoes.php" style="color: gold;">| Instruções</a>
			<a href="adocoesDeSucesso.php" style="color: gold;">| Adoções de Sucesso </a>
			<a href="cadastro_usuario.html"><button class="botao" id="cadastro" style="background-color: black; color: gold; margin-top: 3.5em;">Cadastro</button></a>
			<a href="login_usuario.html"><button class="botao" id="login" style="background-color: black; color: gold; margin-top: 3.5em;">Login</button></a></b>
</nav>