<!-- Barra de Navegação -->
		<nav class="nav1" style="background-color: 	#8A2BE2;">
		<div class="row" align="center">
			<div class="column col-md-3">
				<img src="img/logo.png" height="130em" width="300em" style="margin: 0.5em;">
			</div>
			<div class="column col-md-6" style="margin-top: 3.5em;">
				<b><a href="sobreNos.php" style="color: gold; font-size: 18px;">Sobre Nós</a>
				<a href="sobreOsite.php" style="color: gold; font-size: 18px;">&bull; Sobre o Site</a>
				<a href="home.php" style="color: gold; font-size: 19px;"> &bull; HOME &bull; </a>
				<a href="instrucoes.php" style="color: #FFFF00; font-size: 18px;">Instruções</a>
				<a href="adocoesDeSucesso.php" style="color: gold; font-size: 18px;"> &bull; Adoções de Sucesso </a>
			</div>
			<div class="column col-md-3">
				<a href="cadastro_usuario.php"><button id="cadastro" style="background-color: black; color: gold; margin-top: 3.5em; border-radius: 2em; margin-right: 1em; font-weight: bold;">Cadastro</button></a>
				<a href="login_usuario.php"><button id="login" style="background-color: black; color: gold; margin-top: 3.5em; border-radius: 2em; font-weight: bold;">Login</button></a></b>
				<br><br>
			</div>
	</div>
</nav>