<!-- Barra de Navegação -->
		<nav class="nav1" style="background-color: 	#8A2BE2;">
		<div class="row" align="center">
			<div class="column col-md-3">
				<img src="img/logo.png" height="130em" width="300em" style="margin: 0.5em;">
			</div>
			<div class="column col-md-6" style="margin-top: 3.5em;">
				<b><a href="sobreNos.php" style="color: gold; font-size: 18px;">Sobre Nós</a>
				<a href="sobreOsite.php" style="color: gold; font-size: 18px;">&bull; Sobre o Site</a>
				<a href="home.php" style="color: gold; font-size: 19px;"> &bull; HOME &bull; </a>
				<a href="instrucoes.php" style="color: #FFFF00; font-size: 18px;">Instruções</a>
				<a href="adocoesDeSucesso.php" style="color: gold; font-size: 18px;">&bull; Adoções de Sucesso </a>
			</div>
			<div class="column col-md-3">
				<select name="perfil" onchange="location = this.value;" style="background-color: black; color: gold; border-radius: 5em; margin-top: 3.5em; font-weight: bold; height: 2em; text-align: center;">
					<option selected hidden >Seu Perfil</option>
					<option value="perfil_adm.php">Perfil ADM (Seus Dados)</option>
					<option value="lista_usuarios.php">Edição de Usuários</option>
					<option value="lista_animais_adm.php">Edição de Animais</option>
					<option value="sair.php">Sair</option>
				</select><br><br></b>
			</div>
		</div>
</nav>